BaseURL = 'https://tang-hi.github.io/'
author = "tang donghai"
languageCode = 'en-us'
defaultContentLanguage = "en"
disqusShortname = 'tangdh-life'
title = "Tangdh's Blog"
theme = "Vitae"
paginate = 5
enableRobotsTXT = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "G-D5M6G40M25"


[params]
  
  github = 'tang-hi'

  description = "Learn By Doing"

  avatar = 'avatar.jpeg'
  name = 'tang donghai'
  bio = 'take it easy'
  math = true

  # Show reading time on a post
	readingTime = true 

	# Show word count on a post
	wordCount = true 

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params.comments]
# Enable Comments with "true"
enabled = true
engine = "disqus"

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3


[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5


[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/tang-hi"

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
cmd = "mailto:tangdhcs@gmail.com"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/TangDh"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "index.xml"