site_url: https://tangdh.com/blog/
repo_url: https://github.com/tang-hi/blog
extra:
  analytics:
    provider: google
    property: G-3RY6GDYCPG
plugins:
  - search:
      separator: '[\s\u200b\-]'
theme:
  name: material
  custom_dir: custom
  palette:
    primary: teal 
    accent: indigo
  font:
    text: Mono
    code: fira code
  features:
    - toc.integrate
    - content.code.copy
  logo: ./assets/icon/blog.png
  favicon: ./assets/icon/blog.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

site_name: tang-hi's blog

nav:
  - Paper Reading:
      - MapReduce: "paper/mapreduce.md"
  - C++ stuff:
      - Return Value optimization: "C++/rvo.md"
  - Book:
      - More Effective C++: "books/more-effective-cpp.md"
  - Information Retrieval:
      - 文本相关性: "ir/doc-relv.md"
